{"version":3,"file":"consoleUtils.js","names":["window","console","log","warn","error","_origAssert","assert","conditional","msg","call","Error"],"sources":["../../../../../static/rb/js/utils/consoleUtils.es6.js"],"sourcesContent":["(function() {\n\n\nif (typeof window.console === 'undefined') {\n    window.console = {};\n}\n\nif (typeof console.log === 'undefined') {\n    console.log = function() {};\n}\n\nif (typeof console.warn === 'undefined') {\n    console.warn = function() {};\n}\n\nif (typeof console.error === 'undefined') {\n    console.error = function() {};\n}\n\n\nconst _origAssert = console.assert;\n\n/*\n * console.assert may not behave as we'd hope on all implementations.\n * On Chrome, for instance, it doesn't raise an exception. So, fall back\n * to raising one.\n */\nconsole.assert = function(conditional, msg) {\n    if (_origAssert && _origAssert.call) {\n        _origAssert.call(console, conditional, msg);\n    }\n\n    /* If the above assert never raised an exception, raise our own. */\n    if (!conditional) {\n        throw new Error(msg);\n    }\n};\n\n\n})();\n"],"mappings":";;AAAA,CAAC,YAAW;EAGZ,IAAI,OAAOA,MAAM,CAACC,OAAO,KAAK,WAAW,EAAE;IACvCD,MAAM,CAACC,OAAO,GAAG,CAAC,CAAC;EACvB;EAEA,IAAI,OAAOA,OAAO,CAACC,GAAG,KAAK,WAAW,EAAE;IACpCD,OAAO,CAACC,GAAG,GAAG,YAAW,CAAC,CAAC;EAC/B;EAEA,IAAI,OAAOD,OAAO,CAACE,IAAI,KAAK,WAAW,EAAE;IACrCF,OAAO,CAACE,IAAI,GAAG,YAAW,CAAC,CAAC;EAChC;EAEA,IAAI,OAAOF,OAAO,CAACG,KAAK,KAAK,WAAW,EAAE;IACtCH,OAAO,CAACG,KAAK,GAAG,YAAW,CAAC,CAAC;EACjC;EAGA,MAAMC,WAAW,GAAGJ,OAAO,CAACK,MAAM;;EAElC;AACA;AACA;AACA;AACA;EACAL,OAAO,CAACK,MAAM,GAAG,UAASC,WAAW,EAAEC,GAAG,EAAE;IACxC,IAAIH,WAAW,IAAIA,WAAW,CAACI,IAAI,EAAE;MACjCJ,WAAW,CAACI,IAAI,CAACR,OAAO,EAAEM,WAAW,EAAEC,GAAG,CAAC;IAC/C;;IAEA;IACA,IAAI,CAACD,WAAW,EAAE;MACd,MAAM,IAAIG,KAAK,CAACF,GAAG,CAAC;IACxB;EACJ,CAAC;AAGD,CAAC,GAAG"}